"""add section_heading to chunks

Revision ID: 523a2792a5ca
Revises: 0d5a7cfa563b
Create Date: 2026-09-03 10:20:21.153393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523a2792a5ca'
down_revision: Union[str, Sequence[str], None] = '0d5a7cfa563b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('section_heading', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'section_heading')
    # ### end Alembic commands ###
