"""add fulltext search vector and gin index to chunks

Revision ID: ad1d1c7c2255
Revises: 523a2792a5ca
Create Date: 2026-09-03 12:35:58.739130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad1d1c7c2255'
down_revision: Union[str, Sequence[str], None] = '523a2792a5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('text_search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=False))
    op.create_index('ix_chunks_text_search_gin', 'chunks', ['text_search'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_text_search_gin', table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'text_search')
    # ### end Alembic commands ###
